### ISSUE TITLE
poor connection

### ISSUE THREAD

**Issue by 7s10u** [kitschpatrol/BrainGrapher#3]
Hi i was wondering if you have some tips about getting a better quality connection... here is the problem: sometimes everything works fine and i have really nice quality which drops to poor for some seconds but comes back to normal.. but sometimes it suddenly stops connecting and the mindflex keeps trying to calibrate the headset but can't... is there something i can do? i have my laptop unplugged from the wall outlet...

**Comment by kitschpatrol** [comment]
Getting a solid connection is tricky. Some have reported luck using optoisolators between the Arduino and the TGAM, others have reported success using a dab of conductive gel on the electrode. It's a fickle thing, and up to the TGAM's firmware to decide when a signal is "good enough" to send based on what it's seeing from the electrode.

Closing since this is beyond the scope of the grapher project.

**Comment by xraygun** [comment]
Hi, I think you accidentally CC’d your subscriber list on this. On Nov 19, 2023, at 5:31 PM, Eric Mika ***@***.***> wrote:﻿
Closed #3 as completed.

**Comment by kitschpatrol** [comment]
@xraygun GitHub sends that email because you're subscribed to the issue. : )

**Comment by xraygun** [comment]
oh, ok. thanks. I haven't kept up with this in quite some time.

Cheers
